site_name: My Docs for API course

theme:
  name: dracula
  favicon: logo.png

plugins:
   - swagger-ui-tag:
        background: White
        docExpansion: none
        filter: ""
        syntaxHighlightTheme: monokai

nav:
 - About website: index.md
 - API Docs structure: structure.md
 - API reference: API_ref.md
 - My review: for_me.md

